package com.singtel.assignment.util;

public enum AnimalType {
	BIRD,CHICKEN, DUCK, ROOSTER, PARROT, PARROT_NEAR_DOG,PARROT_NEAR_CAT,PARROT_NEAR_ROOSTER,PARROT_NEAR_DUCK,PARROT_NEAR_PHONE,FISH,SHARK,CLOWN_FISH,DOLPHIN,BUTTERFLY;

}

